### ISSUE TITLE
ਜਦੋਂ ਸਿਹਾਰੀ ਅਤੇ ਪ੍ਰੈਰ ਵਿਚ ਰ ਇਕੱਠੇ ਆ ਜਾਣ

### ISSUE THREAD

**Issue by sikhsiyasat** [prabhjots/font-unicode-convertor#32]
ਜਦੋਂ ਸਿਹਾਰੀ ਅਤੇ ਪ੍ਰੈਰ ਵਿਚ ਰ ਇਕੱਠੇ ਆ ਜਾਣ ਤਾਂ ਅਨਮੋਲ ਤੋਂ ਯੂਨੀਕੋਡ ਵਿਚ ਨਤੀਜਾ ਸਹੀ ਨਹੀਂ ਆਉਂਦਾ।

AnmolLipi Text: AMimRqsr

**Comment by sikhsiyasat** [comment]
This problem occurs from AnmolLipi to Unicode

![Screenshot 2020-03-03 at 7 17 46 PM](https://user-images.githubusercontent.com/16607072/75781773-d5f62a00-5d83-11ea-9171-4fee94ed0b24.png)

**Comment by sikhsiyasat** [comment]
In Anmollipi to AnmolUni this problem is not there

![Screenshot 2020-03-03 at 7 17 55 PM](https://user-images.githubusercontent.com/16607072/75781852-f920d980-5d83-11ea-9bab-f2a14b89f62b.png)

**Comment by prabhjots** [comment]
can you provide expected text in unicode

**Comment by sikhsiyasat** [comment]
ਅੰਮ੍ਰਿਤਸਰ
