### ISSUE TITLE
ਪੈਰ ਵਿੱਚ ਰਾਰਾ ਅਤੇ ਸਿਹਾਰੀ

### ISSUE THREAD

**Issue by sikhsiyasat** [prabhjots/font-unicode-convertor#36]
ਪੈਰ ਵਿੱਚ ਰਾਰਾ ਅਤੇ ਸਿਹਾਰੀ:

ਫੌਂਟ ਕਨਵਰਟਰ ਵਿੱਚ ਪੈਰ ਵਿੱਚ ਰਾਰਾ ਪਾਉਣ ਤੇ ਨਾਲ ਜੇ ਸਿਹਾਰੀ ਲੱਗੇ ਤਾਂ ਰਾਏ ਦੀ ਪੈਰ ਵਿੱਚ ਹਲੰਤ ਬਣ ਕੇ ਰਾਰਾ ਪੂਰਾ ਬਣ ਜਾਂਦਾ ਹੈ।

ਪਰ ਜੇ ਗੂਗਲ ਡੌਕ ਵਿੱਚ ਪੰਜਾਬੀ ਭਾਸ਼ਾ ਚੁਣ ਕੇ ਉਕਤ ਮਾਮਲੇ ਵਾਲਾ ਅੱਖਰ ਲਿਖਿਆ ਜਾਵੇ ਤਾਂ ਅਜਿਹਾ ਨਹੀਂ ਹੁੰਦਾ।

ਦੋ ਦੋਵੇਂ ਅੱਖਰ ਭੇਜ ਰਹੇ ਹਾਂ। ਵੇਖੋ ਕਿ ਦੋਵਾਂ ਦੀ ਕੋਡਿੰਗ ਕੋਈ ਫਰਕ ਵਿਖਾਉਂਦੀ ਹੈ ਤਾਂ ਕਿ ਆਪਣੇ ਕਨਵਰਟਰ ਵਿੱਚ ਦਰੁਸਤ ਕੀਤਾ ਜਾ ਸਕੇ।

Font converter result: ਅੰਮਿ੍ਰਤਸਰ 

Google Doc : ਅੰਮ੍ਰਿਤਸਰ

**Comment by prabhjots** [comment]
Looks like this issue has been closed. @sikhsiyasat please confirm
