### ISSUE TITLE
ਰ ਦੇ ਪੈਰ ਵਿਚ ਹ

### ISSUE THREAD

**Issue by sikhsiyasat** [prabhjots/font-unicode-convertor#4]
ਜਿਥੇ ਰ ਦੇ ਪੈਰ ਵਿਚ ਹ ਆ ਰਹੀ ਹੈ ਉੱਥੇ ਰ ਦੇ ਪੈਰ ਵਿਚ ਹਲੰਤ ਤੋਂ ਬਾਅਦ ਪੂਰਾ ਹ ਪੈ ਰਿਹਾ ਹੈ।

AnmolLipi: vrHygMF

Unicode (After Conversion): ਵਰ੍ਹੇਗੰਢ

**Comment by prabhjots** [comment]
Can you show how to do it right in the unicode font.

**Comment by prabhjots** [comment]
I believe that this is the problem with the unicode font because the "Anmol Unicode" font is fine.

**Comment by sikhsiyasat** [comment]
ok. let me consult some one who works with unicide

**Comment by sikhsiyasat** [comment]
Received this advise:

SSA ji

The issue , we discussed, can be resolved with a simply changed as given below

change the 
font-family: Unicode;
to
font-family: Arial Unicode MS;

Regards,
